name: schedule
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  path_provider: ^1.6.8 
  retrofit: ^1.3.4
  cupertino_icons: ^0.1.2
  json_annotation: ^3.1.1
  provider: any

dev_dependencies:
  retrofit_generator: ^1.4.1
  build_runner: any
  json_serializable: ^3.5.1
  #flutter_test:
  #  sdk: flutter


flutter:
  uses-material-design: true
